# address of the Asset Repository Component
repository.baseUri=http://localhost:8081/

endpoint.context=/
endpoint.port=5200


ski_maintenance.aas.id=urn:samm:at.srfg.passat.ski:1.0.0#SkiMaintenance
ski_maintenance.aas.submodel.id=urn:samm:at.srfg.passat.ski:1.0.0#SkiMaintenance/submodel
ski_maintenance.aas.submodel.requestOperation.idShort=getSkiServiceData
ski_maintenance.aas.submodel.resultOperation.idShort=setSkiServiceResult

# Topic Name
grinding.aas.submodel.event.topic=passat.wp8.grinding.event

# mqtt ssl connection variables
mqtt.ssl.trust.store.path=
mqtt.ssl.trust.store.password=
mqtt.ssl.key.store.path=
mqtt.ssl.key.password=
mqtt.connect.timeout.seconds=10
mqtt.username=
mqtt.password=
#mqtt.broker.clientId=changeme!pass123
#mqtt.broker.userName=changeme
#mqtt.broker.password=pass123
mqtt.server.uri=tcp://localhost:1883
wst.topic.request=wst.jupiter.topic
wst.topic.response=wst.jupiter.topic.response