package at.srfg.iasset.repository.model;

import java.util.Arrays;
import java.util.Base64;

import org.eclipse.aas4j.v3.model.*;
import org.eclipse.aas4j.v3.model.impl.*;

// TODO import org.eclipse.aas4j.v3.rc02.model.impl.DefaultEmbeddedDataSpecification;


public class AASFaultSubmodel {

	public static final String LANGUAGE = "de";

    public static final Submodel SUBMODEL_FAULT1 = createSubmodelForFault();

   
    public static Submodel createSubmodelForFault() {
    	return new DefaultSubmodel.Builder()
    			.idShort("properties")
    			.id("http://iasset.salzburgresearch.at/common/fault")
    			.displayName(new DefaultLangString.Builder()
    					.language(LANGUAGE)
    					.text("i-Asset Fault Submodel").build()
    					)
    			.description(new DefaultLangString.Builder()
    					.language(LANGUAGE)
    					.text("i-Asset OEE Fault Submodel")
    					.build())
    			.kind(ModelingKind.INSTANCE)
    			.submodelElement(new DefaultBasicEventElement.Builder()
    					.idShort("createFault")
    					.direction(Direction.OUTPUT)
    					.state(StateOfEvent.ON)
    					.observed(new DefaultReference.Builder()
    							.type(ReferenceTypes.MODEL_REFERENCE)
    							.key(new DefaultKey.Builder()
    									.type(KeyTypes.SUBMODEL)
    									.value("http://iasset.salzburgresearch.at/common/fault")
    									.build())
    							.key(new DefaultKey.Builder()
    									.type(KeyTypes.SUBMODEL_ELEMENT_COLLECTION)
    									.value("fault")
    									.build())
    							.build())
    					.semanticId(new DefaultReference.Builder()
    							.type(ReferenceTypes.GLOBAL_REFERENCE)
    							.key(new DefaultKey.Builder()
    									.type(KeyTypes.GLOBAL_REFERENCE)
    									.value("http://iasset.salzburgresearch.at/semantic/fault")
    									.build())
    			
    							.build())
    					.build())
    			.submodelElement(new DefaultBasicEventElement.Builder()
    					.idShort("updateFault")
    					.direction(Direction.INPUT)
    					.state(StateOfEvent.ON)
    					.observed(new DefaultReference.Builder()
    							.type(ReferenceTypes.MODEL_REFERENCE)
    							.key(new DefaultKey.Builder()
    									.type(KeyTypes.SUBMODEL)
    									.value("http://iasset.salzburgresearch.at/common/fault")
    									.build())
    							.key(new DefaultKey.Builder()
    									.type(KeyTypes.SUBMODEL_ELEMENT_COLLECTION)
    									.value("fault")
    									.build())
    							.build())
    					.semanticId(new DefaultReference.Builder()
    							.type(ReferenceTypes.GLOBAL_REFERENCE)
    							.key(new DefaultKey.Builder()
    									.type(KeyTypes.GLOBAL_REFERENCE)
    									.value("http://iasset.salzburgresearch.at/semantic/fault")
    									.build())
    			
    							.build())
    					.build())
    			// the belt-info-Type refers to it's parent type
    			.submodelElement(new DefaultSubmodelElementCollection.Builder()
    					.idShort("fault")
    	    			.displayName(new DefaultLangString.Builder()
    	    					.language(LANGUAGE)
    	    					.text("i-Asset Störmeldung Daten").build()
    	    					)
    	    			.value(new DefaultProperty.Builder()
    	    					.idShort("assetId")
    	    	    			.displayName(new DefaultLangString.Builder()
    	    	    					.language(LANGUAGE)
    	    	    					.text("Asset Identifier").build()
    	    	    					)
    	    	    			.valueType(DataTypeDefXsd.STRING)
    	    					.build())
    	    			.value(new DefaultProperty.Builder()
    	    					.idShort("subElementPath")
    	    	    			.displayName(new DefaultLangString.Builder()
    	    	    					.language(LANGUAGE)
    	    	    					.text("Path Subelement").build()
    	    	    					)
    	    	    			.valueType(DataTypeDefXsd.STRING)
    	    					.build())
    	    			.value(new DefaultProperty.Builder()
    	    					.idShort("faultId")
    	    	    			.displayName(new DefaultLangString.Builder()
    	    	    					.language(LANGUAGE)
    	    	    					.text("Fault Identifier").build()
    	    	    					)
    	    	    			.valueType(DataTypeDefXsd.STRING)
    	    					.build())
    	    			.value(new DefaultProperty.Builder()
    	    					.idShort("timestampCreated")
    	    	    			.displayName(new DefaultLangString.Builder()
    	    	    					.language(LANGUAGE)
    	    	    					.text("Timestamp Created").build()
    	    	    					)
    	    	    			.valueType(DataTypeDefXsd.DATE_TIME)
    	    					.build())
    	    			.value(new DefaultProperty.Builder()
    	    					.idShort("timestampFinished")
    	    	    			.displayName(new DefaultLangString.Builder()
    	    	    					.language(LANGUAGE)
    	    	    					.text("Timestamp Created").build()
    	    	    					)
    	    	    			.valueType(DataTypeDefXsd.DATE_TIME)
    	    					.build())
    	    			.value(new DefaultProperty.Builder()
    	    					.idShort("faultCode")
    	    	    			.displayName(new DefaultLangString.Builder()
    	    	    					.language(LANGUAGE)
    	    	    					.text("Fault Code").build()
    	    	    					)
    	    	    			.valueType(DataTypeDefXsd.STRING)
    	    					.build())
    	    			.value(new DefaultProperty.Builder()
    	    					.idShort("shortText")
    	    	    			.displayName(new DefaultLangString.Builder()
    	    	    					.language(LANGUAGE)
    	    	    					.text("Messagetext").build()
    	    	    					)
    	    	    			.valueType(DataTypeDefXsd.STRING)
    	    					.build())
    	    			.value(new DefaultProperty.Builder()
    	    					.idShort("longText")
    	    	    			.displayName(new DefaultLangString.Builder()
    	    	    					.language(LANGUAGE)
    	    	    					.text("Message Description").build()
    	    	    					)
    	    	    			.valueType(DataTypeDefXsd.STRING)
    	    					.build())
    	    			.value(new DefaultProperty.Builder()
    	    					.idShort("priority")
    	    	    			.displayName(new DefaultLangString.Builder()
    	    	    					.language(LANGUAGE)
    	    	    					.text("Priority").build()
    	    	    					)
    	    	    			.valueType(DataTypeDefXsd.INTEGER)
    	    					.build())
    	    			.value(new DefaultProperty.Builder()
    	    					.idShort("senderUserId")
    	    	    			.displayName(new DefaultLangString.Builder()
    	    	    					.language(LANGUAGE)
    	    	    					.text("Benutzer ID Melder").build()
    	    	    					)
    	    	    			.valueType(DataTypeDefXsd.STRING)
    	    					.build())
    	    			.value(new DefaultProperty.Builder()
    	    					.idShort("maintencanceUserId")
    	    	    			.displayName(new DefaultLangString.Builder()
    	    	    					.language(LANGUAGE)
    	    	    					.text("Benutzer ID Sender").build()
    	    	    					)
    	    	    			.valueType(DataTypeDefXsd.STRING)
    	    					.build())
    	    			.value(new DefaultProperty.Builder()
    	    					.idShort("status")
    	    	    			.displayName(new DefaultLangString.Builder()
    	    	    					.language(LANGUAGE)
    	    	    					.text("Fault status").build()
    	    	    					)
    	    	    			.valueType(DataTypeDefXsd.STRING)
    	    					.build())
    	    			
    					.build())
    			.build();
    }

}
